//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLAZAM.Server.Shared.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingsLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLAZAM.Server.Shared.ResourceFiles.SettingsLocalization", typeof(SettingsLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory.
        /// </summary>
        public static string Active_Directory {
            get {
                return ResourceManager.GetString("Active Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string Application_Settings {
            get {
                return ResourceManager.GetString("Application Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base DN.
        /// </summary>
        public static string BaseDN {
            get {
                return ResourceManager.GetString("BaseDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branding Icon.
        /// </summary>
        public static string Branding_Icon {
            get {
                return ResourceManager.GetString("Branding Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Settings.
        /// </summary>
        public static string Email_Settings {
            get {
                return ResourceManager.GetString("Email Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Https.
        /// </summary>
        public static string Force_Https {
            get {
                return ResourceManager.GetString("Force Https", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FQDN.
        /// </summary>
        public static string FQDN {
            get {
                return ResourceManager.GetString("FQDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Address.
        /// </summary>
        public static string From_Address {
            get {
                return ResourceManager.GetString("From Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Display Name.
        /// </summary>
        public static string From_Display_Name {
            get {
                return ResourceManager.GetString("From Display Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage Message.
        /// </summary>
        public static string Homepage_Message {
            get {
                return ResourceManager.GetString("Homepage Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply-To Address.
        /// </summary>
        public static string Reply_To_Address {
            get {
                return ResourceManager.GetString("Reply-To Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply-To Display Name.
        /// </summary>
        public static string Reply_To_Display_Name {
            get {
                return ResourceManager.GetString("Reply-To Display Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Password.
        /// </summary>
        public static string SMTP_Password {
            get {
                return ResourceManager.GetString("SMTP Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Port.
        /// </summary>
        public static string SMTP_Port {
            get {
                return ResourceManager.GetString("SMTP Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Server.
        /// </summary>
        public static string SMTP_Server {
            get {
                return ResourceManager.GetString("SMTP Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Username.
        /// </summary>
        public static string SMTP_Username {
            get {
                return ResourceManager.GetString("SMTP Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SMTP Authentication.
        /// </summary>
        public static string Use_SMTP_Authentication {
            get {
                return ResourceManager.GetString("Use SMTP Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SSL.
        /// </summary>
        public static string Use_SSL {
            get {
                return ResourceManager.GetString("Use SSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TLS.
        /// </summary>
        public static string Use_TLS {
            get {
                return ResourceManager.GetString("Use TLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Helpdesk URL.
        /// </summary>
        public static string User_Helpdesk_URL {
            get {
                return ResourceManager.GetString("User Helpdesk URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Name.
        /// </summary>
        public static string Website_Name {
            get {
                return ResourceManager.GetString("Website Name", resourceCulture);
            }
        }
    }
}
