// <auto-generated />
using System;
using BLAZAM.Common.Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BLAZAM.Common.Migrations.MySql
{
    [DbContext(typeof(MySqlDatabaseContext))]
    partial class MySqlDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AccessLevelFieldAccessMapping", b =>
                {
                    b.Property<int>("AccessLevelsId")
                        .HasColumnType("int");

                    b.Property<int>("FieldMapId")
                        .HasColumnType("int");

                    b.HasKey("AccessLevelsId", "FieldMapId");

                    b.HasIndex("FieldMapId");

                    b.ToTable("AccessLevelFieldAccessMapping");
                });

            modelBuilder.Entity("AccessLevelObjectAccessMapping", b =>
                {
                    b.Property<int>("AccessLevelsId")
                        .HasColumnType("int");

                    b.Property<int>("ObjectMapId")
                        .HasColumnType("int");

                    b.HasKey("AccessLevelsId", "ObjectMapId");

                    b.HasIndex("ObjectMapId");

                    b.ToTable("AccessLevelObjectAccessMapping");
                });

            modelBuilder.Entity("AccessLevelPermissionMapping", b =>
                {
                    b.Property<int>("AccessLevelsId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionMapsId")
                        .HasColumnType("int");

                    b.HasKey("AccessLevelsId", "PermissionMapsId");

                    b.HasIndex("PermissionMapsId");

                    b.ToTable("AccessLevelPermissionMapping");
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.ADSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationBaseDN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FQDN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ServerAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ServerPort")
                        .HasColumnType("int");

                    b.Property<bool>("UseTLS")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ActiveDirectorySettings", t =>
                        {
                            t.HasCheckConstraint("CK_Table_Column", "ADSettingsId = 1");
                        });
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.ActiveDirectoryField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ActiveDirectoryFields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Last Name",
                            FieldName = "sn"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "First Name",
                            FieldName = "givenname"
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "Office",
                            FieldName = "physicalDeliveryOfficeName"
                        },
                        new
                        {
                            Id = 4,
                            DisplayName = "Employee ID",
                            FieldName = "employeeId"
                        },
                        new
                        {
                            Id = 5,
                            DisplayName = "Home Directory",
                            FieldName = "homeDirectory"
                        },
                        new
                        {
                            Id = 6,
                            DisplayName = "Logon Script Path",
                            FieldName = "scriptPath"
                        },
                        new
                        {
                            Id = 7,
                            DisplayName = "Profile Path",
                            FieldName = "profilePath"
                        },
                        new
                        {
                            Id = 8,
                            DisplayName = "Home Phone Number",
                            FieldName = "homePhone"
                        },
                        new
                        {
                            Id = 9,
                            DisplayName = "Street Address",
                            FieldName = "streetAddress"
                        },
                        new
                        {
                            Id = 10,
                            DisplayName = "City",
                            FieldName = "city"
                        },
                        new
                        {
                            Id = 11,
                            DisplayName = "State",
                            FieldName = "st"
                        },
                        new
                        {
                            Id = 12,
                            DisplayName = "Zip Code",
                            FieldName = "postalCode"
                        },
                        new
                        {
                            Id = 13,
                            DisplayName = "Site",
                            FieldName = "site"
                        },
                        new
                        {
                            Id = 14,
                            DisplayName = "Name",
                            FieldName = "name"
                        },
                        new
                        {
                            Id = 15,
                            DisplayName = "Username",
                            FieldName = "samaccountname"
                        },
                        new
                        {
                            Id = 16,
                            DisplayName = "SID",
                            FieldName = "objectSID"
                        },
                        new
                        {
                            Id = 17,
                            DisplayName = "E-Mail Address",
                            FieldName = "mail"
                        },
                        new
                        {
                            Id = 18,
                            DisplayName = "Description",
                            FieldName = "description"
                        },
                        new
                        {
                            Id = 19,
                            DisplayName = "Display Name",
                            FieldName = "displayName"
                        },
                        new
                        {
                            Id = 20,
                            DisplayName = "Distinguished Name",
                            FieldName = "distinguishedName"
                        },
                        new
                        {
                            Id = 21,
                            DisplayName = "Member Of",
                            FieldName = "memberOf"
                        },
                        new
                        {
                            Id = 22,
                            DisplayName = "Company",
                            FieldName = "company"
                        },
                        new
                        {
                            Id = 23,
                            DisplayName = "Title",
                            FieldName = "title"
                        },
                        new
                        {
                            Id = 24,
                            DisplayName = "User Principal Name",
                            FieldName = "userPrincipalName"
                        },
                        new
                        {
                            Id = 25,
                            DisplayName = "Telephone Number",
                            FieldName = "telephoneNumber"
                        },
                        new
                        {
                            Id = 26,
                            DisplayName = "Street",
                            FieldName = "street"
                        },
                        new
                        {
                            Id = 27,
                            DisplayName = "Canonical Name",
                            FieldName = "cn"
                        },
                        new
                        {
                            Id = 28,
                            DisplayName = "Home Drive",
                            FieldName = "homeDrive"
                        },
                        new
                        {
                            Id = 29,
                            DisplayName = "Department",
                            FieldName = "department"
                        },
                        new
                        {
                            Id = 30,
                            DisplayName = "Middle Name",
                            FieldName = "middleName"
                        },
                        new
                        {
                            Id = 31,
                            DisplayName = "Pager",
                            FieldName = "pager"
                        },
                        new
                        {
                            Id = 32,
                            DisplayName = "OS",
                            FieldName = "operatingSystemVersion"
                        },
                        new
                        {
                            Id = 33,
                            DisplayName = "Account Expiration",
                            FieldName = "accountExpires"
                        });
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AnalyticsId")
                        .HasColumnType("longtext");

                    b.Property<string>("AppFQDN")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("AppIcon")
                        .HasColumnType("longblob");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("AutoUpdate")
                        .HasColumnType("tinyint(1)");

                    b.Property<TimeSpan>("AutoUpdateTime")
                        .HasColumnType("time(6)");

                    b.Property<bool>("ForceHTTPS")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("InstallationCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastUpdateCheck")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MOTD")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdateBranch")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserHelpdeskURL")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AppSettings", t =>
                        {
                            t.HasCheckConstraint("CK_Table_Column", "AppSettingsId = 1")
                                .HasName("CK_Table_Column1");
                        });
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Audit.ComputerAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AfterAction")
                        .HasColumnType("longtext");

                    b.Property<string>("BeforeAction")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Target")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ComputerAuditLog");
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Audit.GroupAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AfterAction")
                        .HasColumnType("longtext");

                    b.Property<string>("BeforeAction")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Target")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GroupAuditLog");
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Audit.LogonAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AfterAction")
                        .HasColumnType("longtext");

                    b.Property<string>("BeforeAction")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Target")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("LogonAuditLog");
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Audit.OUAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AfterAction")
                        .HasColumnType("longtext");

                    b.Property<string>("BeforeAction")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Target")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("OUAuditLog");
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Audit.PermissionsAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AfterAction")
                        .HasColumnType("longtext");

                    b.Property<string>("BeforeAction")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Target")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PermissionsAuditLog");
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Audit.RequestAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AfterAction")
                        .HasColumnType("longtext");

                    b.Property<string>("BeforeAction")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Target")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("RequestAuditLog");
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Audit.SettingsAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AfterAction")
                        .HasColumnType("longtext");

                    b.Property<string>("BeforeAction")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Target")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SettingsAuditLog");
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Audit.SystemAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AfterAction")
                        .HasColumnType("longtext");

                    b.Property<string>("BeforeAction")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Target")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SystemAuditLog");
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Audit.UserAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AfterAction")
                        .HasColumnType("longtext");

                    b.Property<string>("BeforeAction")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Target")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UserAuditLog");
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.AuthenticationSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AdminPassword")
                        .HasColumnType("longtext");

                    b.Property<string>("DuoApiHost")
                        .HasColumnType("longtext");

                    b.Property<string>("DuoClientId")
                        .HasColumnType("longtext");

                    b.Property<string>("DuoClientSecret")
                        .HasColumnType("longtext");

                    b.Property<int?>("SessionTimeout")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AuthenticationSettings", t =>
                        {
                            t.HasCheckConstraint("CK_Table_Column", "AuthenticationSettingsId = 1")
                                .HasName("CK_Table_Column2");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminPassword = "password"
                        });
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.EmailSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AdminBcc")
                        .HasColumnType("longtext");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FromAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("FromName")
                        .HasColumnType("longtext");

                    b.Property<string>("ReplyToAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("ReplyToName")
                        .HasColumnType("longtext");

                    b.Property<string>("SMTPPassword")
                        .HasColumnType("longtext");

                    b.Property<int>("SMTPPort")
                        .HasColumnType("int");

                    b.Property<string>("SMTPServer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SMTPUsername")
                        .HasColumnType("longtext");

                    b.Property<bool>("UseSMTPAuth")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("UseTLS")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("EmailSettings", t =>
                        {
                            t.HasCheckConstraint("CK_Table_Column", "EmailSettingsId = 1")
                                .HasName("CK_Table_Column3");
                        });
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BCC")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CC")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplates");
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Permissions.AccessLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AccessLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Deny All"
                        });
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Permissions.ActionAccessFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ObjectActionFlag");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Assign"
                        },
                        new
                        {
                            Id = 2,
                            Name = "UnAssign"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Unlock"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Enable"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Disable"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Rename"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Move"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Create"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Delete"
                        });
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Permissions.ActionAccessMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AccessLevelId")
                        .HasColumnType("int");

                    b.Property<bool>("AllowOrDeny")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ObjectActionId")
                        .HasColumnType("int");

                    b.Property<int>("ObjectType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccessLevelId");

                    b.HasIndex("ObjectActionId");

                    b.ToTable("ActionAccessMapping");
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Permissions.FieldAccessLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FieldAccessLevel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = 10,
                            Name = "Deny"
                        },
                        new
                        {
                            Id = 2,
                            Level = 100,
                            Name = "Read"
                        },
                        new
                        {
                            Id = 3,
                            Level = 1000,
                            Name = "Edit"
                        });
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Permissions.FieldAccessMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ActiveDirectoryFieldId")
                        .HasColumnType("int");

                    b.Property<int>("FieldAccessLevelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActiveDirectoryFieldId");

                    b.HasIndex("FieldAccessLevelId");

                    b.ToTable("AccessLevelFieldMapping");
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Permissions.ObjectAccessLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ObjectAccessLevel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = 10,
                            Name = "Deny"
                        },
                        new
                        {
                            Id = 2,
                            Level = 1000,
                            Name = "Read"
                        });
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Permissions.ObjectAccessMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AllowDisabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ObjectAccessLevelId")
                        .HasColumnType("int");

                    b.Property<int>("ObjectType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObjectAccessLevelId");

                    b.ToTable("AccessLevelObjectMapping");
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Permissions.PermissionDelegate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("DelegateSid")
                        .IsRequired()
                        .HasColumnType("varbinary(3072)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("DelegateSid")
                        .IsUnique();

                    b.ToTable("PermissionDelegate");
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Permissions.PermissionMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OU")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PermissionMap");
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Templates.DirectoryTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("DisplayNameFormula")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ObjectType")
                        .HasColumnType("int");

                    b.Property<string>("ParentOU")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordFormula")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UsernameFormula")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DirectoryTemplates");
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Templates.DirectoryTemplateFieldValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("DirectoryTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DirectoryTemplateId");

                    b.HasIndex("FieldId");

                    b.ToTable("DirectoryTemplateFieldValues");
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Templates.DirectoryTemplateGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("DirectoryTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("GroupSid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DirectoryTemplateId");

                    b.ToTable("DirectoryTemplateGroups");
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.User.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("APIToken")
                        .HasColumnType("longtext");

                    b.Property<bool>("SearchDisabledComputers")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SearchDisabledUsers")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Theme")
                        .HasColumnType("longtext");

                    b.Property<string>("UserGUID")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserGUID")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("PermissionDelegatePermissionMapping", b =>
                {
                    b.Property<int>("PermissionDelegatesId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionsMapsId")
                        .HasColumnType("int");

                    b.HasKey("PermissionDelegatesId", "PermissionsMapsId");

                    b.HasIndex("PermissionsMapsId");

                    b.ToTable("PermissionDelegatePermissionMapping");
                });

            modelBuilder.Entity("AccessLevelFieldAccessMapping", b =>
                {
                    b.HasOne("BLAZAM.Common.Models.Database.Permissions.AccessLevel", null)
                        .WithMany()
                        .HasForeignKey("AccessLevelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BLAZAM.Common.Models.Database.Permissions.FieldAccessMapping", null)
                        .WithMany()
                        .HasForeignKey("FieldMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccessLevelObjectAccessMapping", b =>
                {
                    b.HasOne("BLAZAM.Common.Models.Database.Permissions.AccessLevel", null)
                        .WithMany()
                        .HasForeignKey("AccessLevelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BLAZAM.Common.Models.Database.Permissions.ObjectAccessMapping", null)
                        .WithMany()
                        .HasForeignKey("ObjectMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccessLevelPermissionMapping", b =>
                {
                    b.HasOne("BLAZAM.Common.Models.Database.Permissions.AccessLevel", null)
                        .WithMany()
                        .HasForeignKey("AccessLevelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BLAZAM.Common.Models.Database.Permissions.PermissionMapping", null)
                        .WithMany()
                        .HasForeignKey("PermissionMapsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Permissions.ActionAccessMapping", b =>
                {
                    b.HasOne("BLAZAM.Common.Models.Database.Permissions.AccessLevel", null)
                        .WithMany("ActionMap")
                        .HasForeignKey("AccessLevelId");

                    b.HasOne("BLAZAM.Common.Models.Database.Permissions.ActionAccessFlag", "ObjectAction")
                        .WithMany()
                        .HasForeignKey("ObjectActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjectAction");
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Permissions.FieldAccessMapping", b =>
                {
                    b.HasOne("BLAZAM.Common.Models.Database.ActiveDirectoryField", "Field")
                        .WithMany("FieldAccessMappings")
                        .HasForeignKey("ActiveDirectoryFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BLAZAM.Common.Models.Database.Permissions.FieldAccessLevel", "FieldAccessLevel")
                        .WithMany("FieldAccessMappings")
                        .HasForeignKey("FieldAccessLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("FieldAccessLevel");
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Permissions.ObjectAccessMapping", b =>
                {
                    b.HasOne("BLAZAM.Common.Models.Database.Permissions.ObjectAccessLevel", "ObjectAccessLevel")
                        .WithMany("ObjectAccessMappings")
                        .HasForeignKey("ObjectAccessLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjectAccessLevel");
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Templates.DirectoryTemplateFieldValue", b =>
                {
                    b.HasOne("BLAZAM.Common.Models.Database.Templates.DirectoryTemplate", null)
                        .WithMany("FieldValues")
                        .HasForeignKey("DirectoryTemplateId");

                    b.HasOne("BLAZAM.Common.Models.Database.ActiveDirectoryField", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Templates.DirectoryTemplateGroup", b =>
                {
                    b.HasOne("BLAZAM.Common.Models.Database.Templates.DirectoryTemplate", null)
                        .WithMany("AssignedGroupSids")
                        .HasForeignKey("DirectoryTemplateId");
                });

            modelBuilder.Entity("PermissionDelegatePermissionMapping", b =>
                {
                    b.HasOne("BLAZAM.Common.Models.Database.Permissions.PermissionDelegate", null)
                        .WithMany()
                        .HasForeignKey("PermissionDelegatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BLAZAM.Common.Models.Database.Permissions.PermissionMapping", null)
                        .WithMany()
                        .HasForeignKey("PermissionsMapsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.ActiveDirectoryField", b =>
                {
                    b.Navigation("FieldAccessMappings");
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Permissions.AccessLevel", b =>
                {
                    b.Navigation("ActionMap");
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Permissions.FieldAccessLevel", b =>
                {
                    b.Navigation("FieldAccessMappings");
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Permissions.ObjectAccessLevel", b =>
                {
                    b.Navigation("ObjectAccessMappings");
                });

            modelBuilder.Entity("BLAZAM.Common.Models.Database.Templates.DirectoryTemplate", b =>
                {
                    b.Navigation("AssignedGroupSids");

                    b.Navigation("FieldValues");
                });
#pragma warning restore 612, 618
        }
    }
}
