//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLAZAM.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLAZAM.Localization.AppLocalization", typeof(AppLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Levels.
        /// </summary>
        public static string Access_Levels {
            get {
                return ResourceManager.GetString("Access Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Expiration.
        /// </summary>
        public static string Account_Expiration {
            get {
                return ResourceManager.GetString("Account Expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is disabled..
        /// </summary>
        public static string Account_is_disabled_ {
            get {
                return ResourceManager.GetString("Account is disabled.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is enabled..
        /// </summary>
        public static string Account_is_enabled_ {
            get {
                return ResourceManager.GetString("Account is enabled.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is locked out..
        /// </summary>
        public static string Account_is_locked_out_ {
            get {
                return ResourceManager.GetString("Account is locked out.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is not locked out..
        /// </summary>
        public static string Account_is_not_locked_out_ {
            get {
                return ResourceManager.GetString("Account is not locked out.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string Account_Name {
            get {
                return ResourceManager.GetString("Account Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory.
        /// </summary>
        public static string Active_Directory {
            get {
                return ResourceManager.GetString("Active Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory is not available!.
        /// </summary>
        public static string Active_Directory_is_not_available_ {
            get {
                return ResourceManager.GetString("Active Directory is not available!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory Settings.
        /// </summary>
        public static string Active_Directory_Settings {
            get {
                return ResourceManager.GetString("Active Directory Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Access Level.
        /// </summary>
        public static string Add_New_Access_Level {
            get {
                return ResourceManager.GetString("Add New Access Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additonal Fields.
        /// </summary>
        public static string Additonal_Fields {
            get {
                return ResourceManager.GetString("Additonal Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin bcc.
        /// </summary>
        public static string Admin_bcc {
            get {
                return ResourceManager.GetString("Admin bcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Password.
        /// </summary>
        public static string Admin_Password {
            get {
                return ResourceManager.GetString("Admin Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        public static string Allow {
            get {
                return ResourceManager.GetString("Allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Auto Update.
        /// </summary>
        public static string Allow_Auto_Update {
            get {
                return ResourceManager.GetString("Allow Auto Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Disabled User Access.
        /// </summary>
        public static string Allow_Disabled_User_Access {
            get {
                return ResourceManager.GetString("Allow Disabled User Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name.
        /// </summary>
        public static string Application_Name {
            get {
                return ResourceManager.GetString("Application Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string Application_Settings {
            get {
                return ResourceManager.GetString("Application Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is starting up... please wait....
        /// </summary>
        public static string ApplicationStarting {
            get {
                return ResourceManager.GetString("ApplicationStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Objects.
        /// </summary>
        public static string Assign_Objects {
            get {
                return ResourceManager.GetString("Assign Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign To.
        /// </summary>
        public static string Assign_To {
            get {
                return ResourceManager.GetString("Assign To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to connect to Active Directory..
        /// </summary>
        public static string Attempting_to_connect_to_Active_Directory_ {
            get {
                return ResourceManager.GetString("Attempting to connect to Active Directory.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        public static string Audit {
            get {
                return ResourceManager.GetString("Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Settings.
        /// </summary>
        public static string Authentication_Settings {
            get {
                return ResourceManager.GetString("Authentication Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Update Time.
        /// </summary>
        public static string Auto_Update_Time {
            get {
                return ResourceManager.GetString("Auto Update Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base DN.
        /// </summary>
        public static string Base_DN {
            get {
                return ResourceManager.GetString("Base DN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base DN.
        /// </summary>
        public static string BaseDN {
            get {
                return ResourceManager.GetString("BaseDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branding Icon.
        /// </summary>
        public static string Branding_Icon {
            get {
                return ResourceManager.GetString("Branding Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Change_Password {
            get {
                return ResourceManager.GetString("Change Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose or Search....
        /// </summary>
        public static string Choose_or_Search___ {
            get {
                return ResourceManager.GetString("Choose or Search...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        public static string Computer {
            get {
                return ResourceManager.GetString("Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        public static string Configure {
            get {
                return ResourceManager.GetString("Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Info.
        /// </summary>
        public static string Contact_Info {
            get {
                return ResourceManager.GetString("Contact Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Group.
        /// </summary>
        public static string Create_Group {
            get {
                return ResourceManager.GetString("Create Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Delegation Target.
        /// </summary>
        public static string Create_New_Delegation_Target {
            get {
                return ResourceManager.GetString("Create New Delegation Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create OU.
        /// </summary>
        public static string Create_OU {
            get {
                return ResourceManager.GetString("Create OU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string Create_User {
            get {
                return ResourceManager.GetString("Create User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Login.
        /// </summary>
        public static string Custom_Login {
            get {
                return ResourceManager.GetString("Custom Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database server is not reachable!.
        /// </summary>
        public static string Database_server_is_not_reachable_ {
            get {
                return ResourceManager.GetString("Database server is not reachable!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegates.
        /// </summary>
        public static string Delegates {
            get {
                return ResourceManager.GetString("Delegates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Access Level.
        /// </summary>
        public static string Delete_Access_Level {
            get {
                return ResourceManager.GetString("Delete Access Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delgate Name.
        /// </summary>
        public static string Delgate_Name {
            get {
                return ResourceManager.GetString("Delgate Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny.
        /// </summary>
        public static string Deny {
            get {
                return ResourceManager.GetString("Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard Changes.
        /// </summary>
        public static string Discard_Changes {
            get {
                return ResourceManager.GetString("Discard Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string Display_Name {
            get {
                return ResourceManager.GetString("Display Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Email_Address {
            get {
                return ResourceManager.GetString("Email Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Enabled.
        /// </summary>
        public static string Email_Enabled {
            get {
                return ResourceManager.GetString("Email Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Settings.
        /// </summary>
        public static string Email_Settings {
            get {
                return ResourceManager.GetString("Email Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Id.
        /// </summary>
        public static string Employee_Id {
            get {
                return ResourceManager.GetString("Employee Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Name.
        /// </summary>
        public static string Field_Name {
            get {
                return ResourceManager.GetString("Field Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Type.
        /// </summary>
        public static string Field_Type {
            get {
                return ResourceManager.GetString("Field Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        public static string Fields {
            get {
                return ResourceManager.GetString("Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string First_Name {
            get {
                return ResourceManager.GetString("First Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Https.
        /// </summary>
        public static string Force_Https {
            get {
                return ResourceManager.GetString("Force Https", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FQDN.
        /// </summary>
        public static string FQDN {
            get {
                return ResourceManager.GetString("FQDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Address.
        /// </summary>
        public static string From_Address {
            get {
                return ResourceManager.GetString("From Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Display Name.
        /// </summary>
        public static string From_Display_Name {
            get {
                return ResourceManager.GetString("From Display Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Analytics ID.
        /// </summary>
        public static string Google_Analytics_ID {
            get {
                return ResourceManager.GetString("Google Analytics ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string Group_Name {
            get {
                return ResourceManager.GetString("Group Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Directory.
        /// </summary>
        public static string Home_Directory {
            get {
                return ResourceManager.GetString("Home Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Drive.
        /// </summary>
        public static string Home_Drive {
            get {
                return ResourceManager.GetString("Home Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        public static string Home_Phone {
            get {
                return ResourceManager.GetString("Home Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage Message.
        /// </summary>
        public static string Homepage_Message {
            get {
                return ResourceManager.GetString("Homepage Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impersonate User.
        /// </summary>
        public static string Impersonate_User {
            get {
                return ResourceManager.GetString("Impersonate User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherited Permissions.
        /// </summary>
        public static string Inherited_Permissions {
            get {
                return ResourceManager.GetString("Inherited Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string Job_Title {
            get {
                return ResourceManager.GetString("Job Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Last_Name {
            get {
                return ResourceManager.GetString("Last Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to levelValue.Name.
        /// </summary>
        public static string levelValue_Name {
            get {
                return ResourceManager.GetString("levelValue.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Log_In {
            get {
                return ResourceManager.GetString("Log In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In To Demo.
        /// </summary>
        public static string Log_In_To_Demo {
            get {
                return ResourceManager.GetString("Log In To Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logins.
        /// </summary>
        public static string Logins {
            get {
                return ResourceManager.GetString("Logins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mappings.
        /// </summary>
        public static string Mappings {
            get {
                return ResourceManager.GetString("Mappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string Middle_Name {
            get {
                return ResourceManager.GetString("Middle Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        public static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops.
        /// </summary>
        public static string Oops {
            get {
                return ResourceManager.GetString("Oops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OU.
        /// </summary>
        public static string OU {
            get {
                return ResourceManager.GetString("OU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please report to.
        /// </summary>
        public static string Please_report_to {
            get {
                return ResourceManager.GetString("Please report to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO Box.
        /// </summary>
        public static string PO_Box {
            get {
                return ResourceManager.GetString("PO Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Path.
        /// </summary>
        public static string Profile_Path {
            get {
                return ResourceManager.GetString("Profile Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Settings.
        /// </summary>
        public static string Profile_Settings {
            get {
                return ResourceManager.GetString("Profile Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle Bin.
        /// </summary>
        public static string Recycle_Bin {
            get {
                return ResourceManager.GetString("Recycle Bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply-To Address.
        /// </summary>
        public static string Reply_To_Address {
            get {
                return ResourceManager.GetString("Reply-To Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply-To Display Name.
        /// </summary>
        public static string Reply_To_Display_Name {
            get {
                return ResourceManager.GetString("Reply-To Display Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require change.
        /// </summary>
        public static string Require_change {
            get {
                return ResourceManager.GetString("Require change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string Save_Changes {
            get {
                return ResourceManager.GetString("Save Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Path.
        /// </summary>
        public static string Script_Path {
            get {
                return ResourceManager.GetString("Script Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Timeout.
        /// </summary>
        public static string Session_Timeout {
            get {
                return ResourceManager.GetString("Session Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string Sign_Out {
            get {
                return ResourceManager.GetString("Sign Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Password.
        /// </summary>
        public static string SMTP_Password {
            get {
                return ResourceManager.GetString("SMTP Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Port.
        /// </summary>
        public static string SMTP_Port {
            get {
                return ResourceManager.GetString("SMTP Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Server.
        /// </summary>
        public static string SMTP_Server {
            get {
                return ResourceManager.GetString("SMTP Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Username.
        /// </summary>
        public static string SMTP_Username {
            get {
                return ResourceManager.GetString("SMTP Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop It.
        /// </summary>
        public static string Stop_It {
            get {
                return ResourceManager.GetString("Stop It", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        public static string Street_Address {
            get {
                return ResourceManager.GetString("Street Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Settings.
        /// </summary>
        public static string System_Settings {
            get {
                return ResourceManager.GetString("System Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Category.
        /// </summary>
        public static string Template_Category {
            get {
                return ResourceManager.GetString("Template Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Name.
        /// </summary>
        public static string Template_Name {
            get {
                return ResourceManager.GetString("Template Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        public static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Recipient.
        /// </summary>
        public static string Test_Recipient {
            get {
                return ResourceManager.GetString("Test Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        public static string Unlock {
            get {
                return ResourceManager.GetString("Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Branch.
        /// </summary>
        public static string Update_Branch {
            get {
                return ResourceManager.GetString("Update Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Scheduled.
        /// </summary>
        public static string Update_Scheduled {
            get {
                return ResourceManager.GetString("Update Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Settings.
        /// </summary>
        public static string Update_Settings {
            get {
                return ResourceManager.GetString("Update Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Thumbnail Photo.
        /// </summary>
        public static string Upload_Thumbnail_Photo {
            get {
                return ResourceManager.GetString("Upload Thumbnail Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SMTP Authentication.
        /// </summary>
        public static string Use_SMTP_Authentication {
            get {
                return ResourceManager.GetString("Use SMTP Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SSL.
        /// </summary>
        public static string Use_SSL {
            get {
                return ResourceManager.GetString("Use SSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TLS.
        /// </summary>
        public static string Use_TLS {
            get {
                return ResourceManager.GetString("Use TLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Helpdesk URL.
        /// </summary>
        public static string User_Helpdesk_URL {
            get {
                return ResourceManager.GetString("User Helpdesk URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseTLS.
        /// </summary>
        public static string UseTLS {
            get {
                return ResourceManager.GetString("UseTLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website FQDN.
        /// </summary>
        public static string Website_FQDN {
            get {
                return ResourceManager.GetString("Website FQDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Name.
        /// </summary>
        public static string Website_Name {
            get {
                return ResourceManager.GetString("Website Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string Zip_Code {
            get {
                return ResourceManager.GetString("Zip Code", resourceCulture);
            }
        }
    }
}
