<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>BLAZAM.Plugins</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.19" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BLAZAMFileSystem\BLAZAMFileSystem.csproj" />
    <ProjectReference Include="..\BLAZAMGlobal\BLAZAMGlobal.csproj" />
  </ItemGroup>
</Project>
