<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<ServerGarbageCollection>false</ServerGarbageCollection>
		<AssemblyVersion>1.5.2</AssemblyVersion>
		<Version>2026.03.11.2311</Version>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
		<RootNamespace>BLAZAM</RootNamespace>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);NU1701</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Exceptions\**" />
		<Content Remove="Exceptions\**" />
		<EmbeddedResource Remove="Exceptions\**" />
		<None Remove="Exceptions\**" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="nssm.exe" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Include="..\BLAZAMGui\UI\Inputs\ADAutoComplete.razor.cs" Link="ADAutoComplete.razor.cs" />
	</ItemGroup>








	<ItemGroup>
		<Content Include="nssm.exe">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="static\img\maggie.png">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BlazorTemplater" />
		<PackageReference Include="Cassia" />
		<PackageReference Include="DuoUniversal" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Microsoft.AspNetCore.Components" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" />
		<PackageReference Include="Microsoft.AspNetCore.ResponseCompression" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" />
		<PackageReference Include="Microsoft.Extensions.Http" />
		<PackageReference Include="Microsoft.Extensions.Http.Polly" />
		<PackageReference Include="Microsoft.Extensions.Localization" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="MudBlazor" />
		<PackageReference Include="MudBlazor.ThemeManager" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="Octokit" />
		<PackageReference Include="Polly.Contrib.WaitAndRetry" />
		<PackageReference Include="PreMailer.Net" />
		<PackageReference Include="Serilog" />
		<PackageReference Include="Serilog.Extensions.Logging" />
		<PackageReference Include="Swashbuckle.AspNetCore" />
		<PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
		<PackageReference Include="System.Diagnostics.PerformanceCounter" />
		<PackageReference Include="System.DirectoryServices" />

		<PackageReference Include="System.DirectoryServices.AccountManagement" />

		<PackageReference Include="System.DirectoryServices.Protocols" />

		<PackageReference Include="System.Drawing.Common" />

		<PackageReference Include="System.Management" />

		<PackageReference Include="System.Security.Permissions" />

		<PackageReference Include="Microsoft.CodeAnalysis.Common" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BLAZAMActiveDirectory\BLAZAMActiveDirectory.csproj" />
		<ProjectReference Include="..\BLAZAMCommon\BLAZAMCommon.csproj" />
		<ProjectReference Include="..\BLAZAMDatabase\BLAZAMDatabase.csproj" />
		<ProjectReference Include="..\BLAZAMEmailMessage\BLAZAMEmailMessage.csproj" />
		<ProjectReference Include="..\BLAZAMFileSystem\BLAZAMFileSystem.csproj" />
		<ProjectReference Include="..\BLAZAMGlobal\BLAZAMGlobal.csproj" />
		<ProjectReference Include="..\BLAZAMGui\BLAZAMGui.csproj" />
		<ProjectReference Include="..\BLAZAMJobs\BLAZAMJobs.csproj" />
		<ProjectReference Include="..\BLAZAMLocalization\BLAZAMLocalization.csproj" />
		<ProjectReference Include="..\BLAZAMLoggers\BLAZAMLogger.csproj" />
		<ProjectReference Include="..\BLAZAMNotifications\BLAZAMNotifications.csproj" />
		<ProjectReference Include="..\BLAZAMServices\BLAZAMServices.csproj" />
		<ProjectReference Include="..\BLAZAMSession\BLAZAMSession.csproj" />
		<ProjectReference Include="..\BLAZAMStatic\BLAZAMStatic.csproj" />
		<ProjectReference Include="..\BLAZAMUpdate\BLAZAMUpdate.csproj" />
	</ItemGroup>


	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<Content Update="appsettings.json">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Content>
		<Content Update="wwwroot\favicon.ico">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Update="wwwroot\img\default_logo.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<None Update="license.rtf">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="updater\update.ps1">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Plugins\" />
	</ItemGroup>
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Condition="'$(Configuration)' == 'Debug'" Command="powershell -ExecutionPolicy Unrestricted -NoProfile -NonInteractive -File $(ProjectDir)\IncrementBuildNumber.ps1 -ProjectDir $(ProjectDir) -ProjectPath $(ProjectPath)" />
	</Target>
</Project>

