site_name: Blazam Documentation
repo_url: https://github.com/Blazam-App/BLAZAM
edit_uri: blob/Docs/BLAZAM/docsource
docs_dir: docsource
site_dir: ../docs
theme: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
    - Home: 'index.md'
    - Installation Guide:
        - 'MSI Installer': 'install/msi.md'
        - Manual Installation: 
            - 'Install': 'install/manual.md'
            - 'Configuration': 'install/config.md'
        - Security: 'install/security.md'
    - Permissions:
        - 'Abstract': 'permissions/abstract.md'
    - About:
        - 'License': 'license.md'
        - 'Privacy': 'privacy.md'
