<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>BLAZAM.EmailMessage</RootNamespace>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.Components" />
	  <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
	  <PackageReference Include="Microsoft.Extensions.Localization" />
	  <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" />
	  <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="MudBlazor" />
    <PackageReference Include="MudBlazor.Markdown" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" />
    <PackageReference Include="System.DirectoryServices.Protocols" />
    <PackageReference Include="System.Management" />
    <PackageReference Include="System.Security.Permissions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BLAZAMDatabase\BLAZAMDatabase.csproj" />
    <ProjectReference Include="..\BLAZAMLocalization\BLAZAMLocalization.csproj" />
    <ProjectReference Include="..\BLAZAMStatic\BLAZAMStatic.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Email\Messages\AccessRequestEmailMessage.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Update="Email\Messages\LockedOutEmailMessage.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>

</Project>
