<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  <disabletransitiveprojectreferences>true</disabletransitiveprojectreferences>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="8.0.19" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.19" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.19"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BLAZAMActiveDirectory\BLAZAMActiveDirectory.csproj">
      
      
    </ProjectReference>
    <ProjectReference Include="..\BLAZAMDatabase\BLAZAMDatabase.csproj">
      
      <CopyLocalSatelliteAssemblies>True</CopyLocalSatelliteAssemblies>
    </ProjectReference>
    <ProjectReference Include="..\BLAZAMGlobal\BLAZAMGlobal.csproj">
      
      
    </ProjectReference>
    <ProjectReference Include="..\BLAZAMGui\BLAZAMGui.csproj">
      
      
    </ProjectReference>
    <ProjectReference Include="..\BLAZAMNotifications\BLAZAMNotifications.csproj">
      
      
    </ProjectReference>
    <ProjectReference Include="..\BLAZAMPlugins\BLAZAMPlugins.csproj">
      
      
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resource1.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource1.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resource1.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource1.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
