<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>BLAZAM.Themes</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="8.0.12" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="8.0.12" />
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.1" />
    <PackageReference Include="MudBlazor" Version="7.15.0" />
    <PackageReference Include="MudBlazor.ThemeManager" Version="2.1.0" />
  </ItemGroup>

</Project>
