<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>BLAZAM.Gui</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Helpers\**" />
		<Compile Remove="UI\General\**" />
		<Compile Remove="wwwroot\**" />
		<Content Remove="Helpers\**" />
		<Content Remove="UI\General\**" />
		<Content Remove="wwwroot\**" />
		<EmbeddedResource Remove="Helpers\**" />
		<EmbeddedResource Remove="UI\General\**" />
		<EmbeddedResource Remove="wwwroot\**" />
		<None Remove="Helpers\**" />
		<None Remove="UI\General\**" />
		<None Remove="wwwroot\**" />
	</ItemGroup>


	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="DuoUniversal" />
		<PackageReference Include="MailKit" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
		<PackageReference Include="Microsoft.AspNetCore.Components" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="Microsoft.Extensions.Http" />
		<PackageReference Include="Microsoft.Extensions.Localization" />
		<PackageReference Include="Microsoft.Extensions.Localization.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="MudBlazor" />
		<PackageReference Include="MudBlazor.Markdown" />
		<PackageReference Include="Octokit" />
		<PackageReference Include="PreMailer.Net" />
		<PackageReference Include="Serilog" />
		<PackageReference Include="Serilog.Extensions.Logging" />
		<PackageReference Include="SixLabors.ImageSharp" />
		<PackageReference Include="System.Diagnostics.PerformanceCounter" />
		<PackageReference Include="System.DirectoryServices.Protocols" />
		<PackageReference Include="System.Drawing.Common" />
		<PackageReference Include="System.Management" />
		<PackageReference Include="System.Security.Permissions" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BLAZAMActiveDirectory\BLAZAMActiveDirectory.csproj" />
		<ProjectReference Include="..\BLAZAMCommon\BLAZAMCommon.csproj" />
		<ProjectReference Include="..\BLAZAMGlobal\BLAZAMGlobal.csproj" />
		<ProjectReference Include="..\BLAZAMLocalization\BLAZAMLocalization.csproj" />
		<ProjectReference Include="..\BLAZAMLoggers\BLAZAMLogger.csproj" />
		<ProjectReference Include="..\BLAZAMServices\BLAZAMServices.csproj" />
		<ProjectReference Include="..\BLAZAMSession\BLAZAMSession.csproj" />
		<ProjectReference Include="..\BLAZAMThemes\BLAZAMThemes.csproj" />
		<ProjectReference Include="..\BLAZAMUpdate\BLAZAMUpdate.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="ApplicationNews">
	    <HintPath>..\BLAZAMServices\ApplicationNews.dll</HintPath>
	  </Reference>
	</ItemGroup>

	<ItemGroup>
	  <Content Update="UI\Dashboard\Widgets\NewContactsWidget.razor">
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	  </Content>
	  <Content Update="UI\Dashboard\Widgets\StaleEntriesWidgetDataGrid.razor">
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	  </Content>
	  <Content Update="UI\Dashboard\Widgets\StaleComputersWidget.razor">
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	  </Content>
	  <Content Update="UI\Outputs\BitLockerViewer.razor">
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	  </Content>
	  <Content Update="UI\OU\CreateOU.razor">
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	  </Content>
	</ItemGroup>


</Project>
