<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>BLAZAM.Services</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DuoUniversal" />
    <PackageReference Include="GoogleAuthenticator" />
    <PackageReference Include="MailKit" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Localization" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="MudBlazor" />
    <PackageReference Include="Octokit" />
    <PackageReference Include="PreMailer.Net" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="System.DirectoryServices.Protocols" />
    <PackageReference Include="System.Management" />
    <PackageReference Include="System.Security.Permissions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BLAZAMActiveDirectory\BLAZAMActiveDirectory.csproj" />
    <ProjectReference Include="..\BLAZAMCommon\BLAZAMCommon.csproj" />
    <ProjectReference Include="..\BLAZAMDatabase\BLAZAMDatabase.csproj" />
    <ProjectReference Include="..\BLAZAMGlobal\BLAZAMGlobal.csproj" />
    <ProjectReference Include="..\BLAZAMSession\BLAZAMSession.csproj" />
    <ProjectReference Include="..\BLAZAMUpdate\BLAZAMUpdate.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ApplicationNews">
      <HintPath>ApplicationNews.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Session\" />
  </ItemGroup>

</Project>
