<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>BLAZAM.Update</RootNamespace>
		<NoWarn>$(NoWarn);NU1701</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="Microsoft.Extensions.Http" />
		<PackageReference Include="Microsoft.Extensions.Localization" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="MudBlazor" />
		<PackageReference Include="MudBlazor.Markdown" />
		<PackageReference Include="Octokit" />
		<PackageReference Include="PreMailer.Net" />
		<PackageReference Include="Serilog" />
		<PackageReference Include="Serilog.Extensions.Logging" />
		<PackageReference Include="SixLabors.ImageSharp" />
		<PackageReference Include="System.Diagnostics.PerformanceCounter" />
		<PackageReference Include="System.DirectoryServices.Protocols" />
		<PackageReference Include="System.Drawing.Common" />
		<PackageReference Include="System.Management" />
		<PackageReference Include="System.Security.Permissions" />
		<PackageReference Include="TaskScheduler" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BLAZAMCommon\BLAZAMCommon.csproj" />
		<ProjectReference Include="..\BLAZAMDatabase\BLAZAMDatabase.csproj" />
		<ProjectReference Include="..\BLAZAMFileSystem\BLAZAMFileSystem.csproj" />
		<ProjectReference Include="..\BLAZAMJobs\BLAZAMJobs.csproj" />
		<ProjectReference Include="..\BLAZAMLocalization\BLAZAMLocalization.csproj" />
		<ProjectReference Include="..\BLAZAMLoggers\BLAZAMLogger.csproj" />
	</ItemGroup>

</Project>
