<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>BLAZAM.Update</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components" Version="8.0.17" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.17" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="9.0.6" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.6">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.6" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.6" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="9.0.6" />
		<PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.6" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.6" />
		<PackageReference Include="MudBlazor" Version="8.8.0" />
		<PackageReference Include="MudBlazor.Markdown" Version="8.7.0" />
		<PackageReference Include="Octokit" Version="14.0.0" />
		<PackageReference Include="PreMailer.Net" Version="2.7.0" />
		<PackageReference Include="Serilog" Version="4.3.0" />
		<PackageReference Include="Serilog.Extensions.Logging" Version="9.0.2" />
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.10" />
		<PackageReference Include="System.Diagnostics.PerformanceCounter" Version="9.0.6" />
		<PackageReference Include="System.DirectoryServices.Protocols" Version="9.0.6" />
		<PackageReference Include="System.Drawing.Common" Version="9.0.6" />
		<PackageReference Include="System.Management" Version="9.0.6" />
		<PackageReference Include="System.Security.Permissions" Version="9.0.6" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BLAZAMCommon\BLAZAMCommon.csproj" />
		<ProjectReference Include="..\BLAZAMDatabase\BLAZAMDatabase.csproj" />
		<ProjectReference Include="..\BLAZAMFileSystem\BLAZAMFileSystem.csproj" />
		<ProjectReference Include="..\BLAZAMJobs\BLAZAMJobs.csproj" />
		<ProjectReference Include="..\BLAZAMLocalization\BLAZAMLocalization.csproj" />
		<ProjectReference Include="..\BLAZAMLoggers\BLAZAMLogger.csproj" />
	</ItemGroup>

</Project>
