// <auto-generated />
using System;
using BLAZAM.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BLAZAM.Common.Migrations.Sqlite
{
    [DbContext(typeof(SqliteDatabaseContext))]
    partial class SqliteDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("AccessLevelFieldAccessMapping", b =>
                {
                    b.Property<int>("AccessLevelsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldMapId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccessLevelsId", "FieldMapId");

                    b.HasIndex("FieldMapId");

                    b.ToTable("AccessLevelFieldAccessMapping");
                });

            modelBuilder.Entity("AccessLevelObjectAccessMapping", b =>
                {
                    b.Property<int>("AccessLevelsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObjectMapId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccessLevelsId", "ObjectMapId");

                    b.HasIndex("ObjectMapId");

                    b.ToTable("AccessLevelObjectAccessMapping");
                });

            modelBuilder.Entity("AccessLevelPermissionMapping", b =>
                {
                    b.Property<int>("AccessLevelsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermissionMapsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccessLevelsId", "PermissionMapsId");

                    b.HasIndex("PermissionMapsId");

                    b.ToTable("AccessLevelPermissionMapping");
                });

            modelBuilder.Entity("AppUserChatRoom", b =>
                {
                    b.Property<int>("ChatRoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MembersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChatRoomId", "MembersId");

                    b.HasIndex("MembersId");

                    b.ToTable("AppUserChatRoom");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.ADSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationBaseDN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FQDN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ServerPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseTLS")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ActiveDirectorySettings", t =>
                        {
                            t.HasCheckConstraint("CK_Table_Column", "[Id] = 1");
                        });
                });

            modelBuilder.Entity("BLAZAM.Database.Models.ActiveDirectoryField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FieldType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ActiveDirectoryFields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Last Name",
                            FieldName = "sn",
                            FieldType = 0,
                            PropertyName = "Sn"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "First Name",
                            FieldName = "givenname",
                            FieldType = 0,
                            PropertyName = "GivenName"
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "Office",
                            FieldName = "physicalDeliveryOfficeName",
                            FieldType = 0,
                            PropertyName = "PhysicalDeliveryOfficeName"
                        },
                        new
                        {
                            Id = 4,
                            DisplayName = "Employee Id",
                            FieldName = "employeeId",
                            FieldType = 0,
                            PropertyName = "EmployeeId"
                        },
                        new
                        {
                            Id = 5,
                            DisplayName = "Home Directory",
                            FieldName = "homeDirectory",
                            FieldType = 0,
                            PropertyName = "HomeDirectory"
                        },
                        new
                        {
                            Id = 6,
                            DisplayName = "Logon Script Path",
                            FieldName = "scriptPath",
                            FieldType = 0,
                            PropertyName = "ScriptPath"
                        },
                        new
                        {
                            Id = 7,
                            DisplayName = "Profile Path",
                            FieldName = "profilePath",
                            FieldType = 0,
                            PropertyName = "ProfilePath"
                        },
                        new
                        {
                            Id = 8,
                            DisplayName = "Home Phone Number",
                            FieldName = "homePhone",
                            FieldType = 0,
                            PropertyName = "HomePhone"
                        },
                        new
                        {
                            Id = 9,
                            DisplayName = "Street Address",
                            FieldName = "streetAddress",
                            FieldType = 0,
                            PropertyName = "StreetAddress"
                        },
                        new
                        {
                            Id = 10,
                            DisplayName = "City",
                            FieldName = "l",
                            FieldType = 0,
                            PropertyName = "City"
                        },
                        new
                        {
                            Id = 11,
                            DisplayName = "State",
                            FieldName = "st",
                            FieldType = 0,
                            PropertyName = "State"
                        },
                        new
                        {
                            Id = 12,
                            DisplayName = "Zip Code",
                            FieldName = "postalCode",
                            FieldType = 0,
                            PropertyName = "Zip"
                        },
                        new
                        {
                            Id = 13,
                            DisplayName = "Site",
                            FieldName = "site",
                            FieldType = 0,
                            PropertyName = "Site"
                        },
                        new
                        {
                            Id = 14,
                            DisplayName = "Name",
                            FieldName = "name",
                            FieldType = 0,
                            PropertyName = "Name"
                        },
                        new
                        {
                            Id = 15,
                            DisplayName = "Username",
                            FieldName = "samaccountname",
                            FieldType = 0,
                            PropertyName = "SAMAccountName"
                        },
                        new
                        {
                            Id = 16,
                            DisplayName = "SID",
                            FieldName = "objectSID",
                            FieldType = 2,
                            PropertyName = "SID"
                        },
                        new
                        {
                            Id = 17,
                            DisplayName = "E-Mail Address",
                            FieldName = "mail",
                            FieldType = 0,
                            PropertyName = "Email"
                        },
                        new
                        {
                            Id = 18,
                            DisplayName = "Description",
                            FieldName = "description",
                            FieldType = 0,
                            PropertyName = "Description"
                        },
                        new
                        {
                            Id = 19,
                            DisplayName = "Display Name",
                            FieldName = "displayName",
                            FieldType = 0,
                            PropertyName = "DisplayName"
                        },
                        new
                        {
                            Id = 20,
                            DisplayName = "Distinguished Name",
                            FieldName = "distinguishedName",
                            FieldType = 0,
                            PropertyName = "DN"
                        },
                        new
                        {
                            Id = 21,
                            DisplayName = "Member Of",
                            FieldName = "memberOf",
                            FieldType = 4,
                            PropertyName = "MemberOf"
                        },
                        new
                        {
                            Id = 22,
                            DisplayName = "Company",
                            FieldName = "company",
                            FieldType = 0,
                            PropertyName = "Company"
                        },
                        new
                        {
                            Id = 23,
                            DisplayName = "Title",
                            FieldName = "title",
                            FieldType = 0,
                            PropertyName = "Title"
                        },
                        new
                        {
                            Id = 24,
                            DisplayName = "User Principal Name",
                            FieldName = "userPrincipalName",
                            FieldType = 0,
                            PropertyName = "UserPrincipalName"
                        },
                        new
                        {
                            Id = 25,
                            DisplayName = "Telephone Number",
                            FieldName = "telephoneNumber",
                            FieldType = 0,
                            PropertyName = "TelephoneNumber"
                        },
                        new
                        {
                            Id = 26,
                            DisplayName = "PO Box",
                            FieldName = "postOfficeBox",
                            FieldType = 0,
                            PropertyName = "POBox"
                        },
                        new
                        {
                            Id = 27,
                            DisplayName = "Canonical Name",
                            FieldName = "cn",
                            FieldType = 0,
                            PropertyName = "CanonicalName"
                        },
                        new
                        {
                            Id = 28,
                            DisplayName = "Home Drive",
                            FieldName = "homeDrive",
                            FieldType = 3,
                            PropertyName = "HomeDrive"
                        },
                        new
                        {
                            Id = 29,
                            DisplayName = "Department",
                            FieldName = "department",
                            FieldType = 0,
                            PropertyName = "Department"
                        },
                        new
                        {
                            Id = 30,
                            DisplayName = "Middle Name",
                            FieldName = "middleName",
                            FieldType = 0,
                            PropertyName = "MiddleName"
                        },
                        new
                        {
                            Id = 31,
                            DisplayName = "Pager",
                            FieldName = "pager",
                            FieldType = 0,
                            PropertyName = "Pager"
                        },
                        new
                        {
                            Id = 32,
                            DisplayName = "OS",
                            FieldName = "operatingSystemVersion",
                            FieldType = 0,
                            PropertyName = "OS"
                        },
                        new
                        {
                            Id = 33,
                            DisplayName = "Account Expiration",
                            FieldName = "accountExpires",
                            FieldType = 5,
                            PropertyName = "ExpireTime"
                        },
                        new
                        {
                            Id = 34,
                            DisplayName = "Manager",
                            FieldName = "manager",
                            FieldType = 0,
                            PropertyName = "Manager"
                        },
                        new
                        {
                            Id = 35,
                            DisplayName = "Photo",
                            FieldName = "thumbnail",
                            FieldType = 2,
                            PropertyName = "ThumbnailPhoto"
                        },
                        new
                        {
                            Id = 36,
                            DisplayName = "Log On To",
                            FieldName = "userWorkstations",
                            FieldType = 0,
                            PropertyName = "LogOnTo"
                        },
                        new
                        {
                            Id = 37,
                            DisplayName = "Logon Hours",
                            FieldName = "logonHours",
                            FieldType = 2,
                            PropertyName = "LogonHours"
                        },
                        new
                        {
                            Id = 38,
                            DisplayName = "Group Type",
                            FieldName = "groupType",
                            FieldType = 2,
                            PropertyName = "GroupType"
                        },
                        new
                        {
                            Id = 39,
                            DisplayName = "Group Scope",
                            FieldName = "groupType",
                            FieldType = 2,
                            PropertyName = "GroupScope"
                        },
                        new
                        {
                            Id = 40,
                            DisplayName = "Enabled",
                            FieldName = "userAccountControl",
                            FieldType = 6,
                            PropertyName = "Enabled"
                        },
                        new
                        {
                            Id = 41,
                            DisplayName = "Locked Out",
                            FieldName = "lockoutTime",
                            FieldType = 5,
                            PropertyName = "LockedOut"
                        },
                        new
                        {
                            Id = 42,
                            DisplayName = "OU",
                            FieldName = "ou",
                            FieldType = 0,
                            PropertyName = "OU"
                        },
                        new
                        {
                            Id = 43,
                            DisplayName = "Last Change",
                            FieldName = "whenChanged",
                            FieldType = 1,
                            PropertyName = "LastChanged"
                        },
                        new
                        {
                            Id = 44,
                            DisplayName = "Last Logon",
                            FieldName = "lastLogonTimestamp",
                            FieldType = 1,
                            PropertyName = "LastLogonTimestamp"
                        },
                        new
                        {
                            Id = 45,
                            DisplayName = "LAPS Password",
                            FieldName = "msLAPS-Password",
                            FieldType = 0,
                            PropertyName = "LapsPassword"
                        });
                });

            modelBuilder.Entity("BLAZAM.Database.Models.ActiveDirectoryFieldObjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveDirectoryFieldId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomActiveDirectoryFieldId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObjectType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomActiveDirectoryFieldId");

                    b.ToTable("ActiveDirectoryFieldObjectMappings");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnalyticsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppFQDN")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("AppIcon")
                        .HasColumnType("BLOB");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoUpdate")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("AutoUpdateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ForceHTTPS")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InstallationCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUpdateCheck")
                        .HasColumnType("TEXT");

                    b.Property<string>("MOTD")
                        .HasColumnType("TEXT");

                    b.Property<string>("MyrtilleURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("SSLCertificateCipher")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SendDeveloperAnalytics")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SendLogsToDeveloper")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdateBranch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateDomain")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatePassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateUsername")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseUpdateCredentials")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserHelpdeskURL")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings", t =>
                        {
                            t.HasCheckConstraint("CK_Table_Column", "[Id] = 1");
                        });
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Audit.DirectoryEntryAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterAction")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeAction")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DirectoryEntryAuditLogs");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Audit.EmailAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bcc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cc")
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .HasColumnType("TEXT");

                    b.Property<string>("HtmlBody")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastAttemptTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageGuid")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReadTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Retries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerResponse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmailAuditLog");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Audit.LogonAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterAction")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeAction")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LogonAuditLog");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Audit.PermissionsAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterAction")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeAction")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PermissionsAuditLog");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Audit.RequestAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterAction")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeAction")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RequestAuditLog");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Audit.SettingsAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterAction")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeAction")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SettingsAuditLog");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Audit.SystemAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterAction")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeAction")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SystemAuditLog");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.AuthenticationSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DuoApiHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("DuoClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DuoClientSecret")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DuoEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DuoUnreachableBehavior")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MFAType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequireMFA")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SessionTimeout")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AuthenticationSettings", t =>
                        {
                            t.HasCheckConstraint("CK_Table_Column", "[Id] = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminPassword = "password",
                            DuoEnabled = false,
                            DuoUnreachableBehavior = 0,
                            MFAType = 0,
                            RequireMFA = false,
                            SessionTimeout = 15
                        });
                });

            modelBuilder.Entity("BLAZAM.Database.Models.AutomationRuleExcludedGroupSid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GlobalAutomationRuleSettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GlobalAutomationRuleSettingsId");

                    b.ToTable("AutomationRuleExcludedGroupSid");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Chat.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatRoomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChatRoomId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Chat.ChatRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MembersHash")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChatRooms");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Chat.UnreadChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatRoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChatMessageId");

                    b.ToTable("UnreadChatMessages");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.CustomActiveDirectoryField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FieldType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CustomActiveDirectoryFields");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.EmailSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminBcc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplyToAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplyToName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SMTPPassword")
                        .HasColumnType("TEXT");

                    b.Property<int>("SMTPPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SMTPServer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SMTPUsername")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseSMTPAuth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseTLS")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EmailSettings", t =>
                        {
                            t.HasCheckConstraint("CK_Table_Column", "[Id] = 1");
                        });
                });

            modelBuilder.Entity("BLAZAM.Database.Models.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TemplateType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplates");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.FailedADLogonEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Sid")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkstationIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkstationName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FailedADLogonEvents");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.LockedOutUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Added")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LockedOutUsers");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Notifications.NotificationSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Block")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ByEmail")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("InApp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OU")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationSubscriptions");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Notifications.SubscriptionNotificationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotificationSubscriptionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotificationType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NotificationSubscriptionId");

                    b.ToTable("SubscriptionNotificationType");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Notifications.SubscriptionWebHookType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotificationType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WebHookSubscriptionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WebHookSubscriptionId");

                    b.ToTable("SubscriptionWebHookType");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Notifications.WebHookAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Delivered")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastAttemptTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MessageGuid")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResponseCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseHeaders")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Signature")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WebHookSubscriptionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WebHookSubscriptionId");

                    b.ToTable("WebHookAttempts");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Notifications.WebHookSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorizationToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HmacKey")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IgnoreSSLVerification")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OU")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrivateKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WebHookAuthorization")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WebHookMethod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WebHookSignature")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WebHookSubscriptions");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Permissions.AccessLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AccessLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Deny All"
                        });
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Permissions.ActionAccessMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccessLevelId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowOrDeny")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObjectActionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObjectType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccessLevelId");

                    b.HasIndex("ObjectActionId");

                    b.ToTable("ActionAccessMapping");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Permissions.FieldAccessLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FieldAccessLevel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = 10,
                            Name = "Deny"
                        },
                        new
                        {
                            Id = 2,
                            Level = 100,
                            Name = "Read"
                        },
                        new
                        {
                            Id = 3,
                            Level = 1000,
                            Name = "Edit"
                        });
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Permissions.FieldAccessMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomFieldId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldAccessLevelId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FieldId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObjectType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomFieldId");

                    b.HasIndex("FieldAccessLevelId");

                    b.HasIndex("FieldId");

                    b.ToTable("AccessLevelFieldMapping");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Permissions.GlobalPermissionRequestAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObjectAction")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GlobalPermissionRequestActions");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Permissions.GlobalPermissionSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowAccessRequest")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowSelfModification")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GlobalPermissionSettings");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Permissions.ObjectAccessLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ObjectAccessLevel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = 10,
                            Name = "Deny"
                        },
                        new
                        {
                            Id = 2,
                            Level = 1000,
                            Name = "Read"
                        });
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Permissions.ObjectAccessMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ObjectAccessLevelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObjectType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ObjectAccessLevelId");

                    b.ToTable("AccessLevelObjectMapping");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Permissions.ObjectAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ObjectActionFlag");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = 4,
                            Name = "Assign"
                        },
                        new
                        {
                            Id = 2,
                            Action = 3,
                            Name = "UnAssign"
                        },
                        new
                        {
                            Id = 3,
                            Action = 8,
                            Name = "Unlock"
                        },
                        new
                        {
                            Id = 4,
                            Action = 5,
                            Name = "Enable"
                        },
                        new
                        {
                            Id = 5,
                            Action = 6,
                            Name = "Disable"
                        },
                        new
                        {
                            Id = 6,
                            Action = 7,
                            Name = "Rename"
                        },
                        new
                        {
                            Id = 7,
                            Action = 0,
                            Name = "Move"
                        },
                        new
                        {
                            Id = 8,
                            Action = 2,
                            Name = "Create"
                        },
                        new
                        {
                            Id = 9,
                            Action = 1,
                            Name = "Delete"
                        },
                        new
                        {
                            Id = 10,
                            Action = 9,
                            Name = "Set Password"
                        });
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Permissions.PermissionDelegate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DelegateName")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("DelegateSid")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DelegateSid")
                        .IsUnique();

                    b.ToTable("PermissionDelegate");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Permissions.PermissionMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OU")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PermissionMap");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Rules.AutomationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveDirectoryObjectType")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("DaysOfWeekToRun")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IntervalCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastExcecuted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastTriggered")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ScheduleInterval")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("ScheduledRunTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("StopOnThisRule")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Trigger")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AutomationRules");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Rules.AutomationRuleAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ActionGuid")
                        .HasColumnType("TEXT");

                    b.Property<int>("ActionType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AutomationRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AutomationRuleId");

                    b.ToTable("AutomationRuleActions");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Rules.AutomationRuleActionFieldValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutomationRuleActionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomFieldId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FieldId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AutomationRuleActionId");

                    b.HasIndex("CustomFieldId");

                    b.HasIndex("FieldId");

                    b.ToTable("AutomationRuleFieldValues");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Rules.AutomationRuleAndFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomFieldId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FieldId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FilterGuid")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Negate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Operator")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrFilterId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TimeFrame")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomFieldId");

                    b.HasIndex("FieldId");

                    b.HasIndex("OrFilterId");

                    b.ToTable("AutomationRuleAndFilters");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Rules.AutomationRuleGroupSid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Assigned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutomationRuleActionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupSid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AutomationRuleActionId");

                    b.ToTable("AutomationRuleGroupSids");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Rules.AutomationRuleOrFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutomationRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FilterGuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AutomationRuleId");

                    b.ToTable("AutomationRuleOrFilter");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Rules.GlobalAutomationRuleSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GlobalAutomationRuleSettings");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Templates.DirectoryTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("AllowCustomGroups")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("AllowUsernameOverride")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("AskForAlternateEmail")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayNameFormula")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ObjectType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentOU")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordFormula")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("RequirePasswordChange")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SendWelcomeEmail")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsernameFormula")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Visible")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentTemplateId");

                    b.ToTable("DirectoryTemplates");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Templates.DirectoryTemplateFieldValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomFieldId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DirectoryTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Editable")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FieldId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Required")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomFieldId");

                    b.HasIndex("DirectoryTemplateId");

                    b.HasIndex("FieldId");

                    b.ToTable("DirectoryTemplateFieldValues");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Templates.DirectoryTemplateGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DirectoryTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupSid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DirectoryTemplateId");

                    b.ToTable("DirectoryTemplateGroups");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.User.ApiToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenHash")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ApiTokens");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.User.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthenticatorSecret")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("BLOB");

                    b.Property<bool>("SearchDisabledComputers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SearchDisabledUsers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Theme")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserGUID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserGUID")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.User.NotificationMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomFieldId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Dismissable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Expires")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FieldId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<int>("MessageType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetDN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("NotificationMessages");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.User.ReadNewsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("NewsItemId")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("NewsItemUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ReadNewsItems");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.User.UserDashboardWidget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemsPerPage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WidgetType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserDashboardWidgets");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.User.UserFavoriteEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserFavoriteEntries");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.User.UserNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotificationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("PermissionDelegatePermissionMapping", b =>
                {
                    b.Property<int>("PermissionDelegatesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermissionsMapsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PermissionDelegatesId", "PermissionsMapsId");

                    b.HasIndex("PermissionsMapsId");

                    b.ToTable("PermissionDelegatePermissionMapping");
                });

            modelBuilder.Entity("AccessLevelFieldAccessMapping", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.Permissions.AccessLevel", null)
                        .WithMany()
                        .HasForeignKey("AccessLevelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BLAZAM.Database.Models.Permissions.FieldAccessMapping", null)
                        .WithMany()
                        .HasForeignKey("FieldMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccessLevelObjectAccessMapping", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.Permissions.AccessLevel", null)
                        .WithMany()
                        .HasForeignKey("AccessLevelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BLAZAM.Database.Models.Permissions.ObjectAccessMapping", null)
                        .WithMany()
                        .HasForeignKey("ObjectMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccessLevelPermissionMapping", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.Permissions.AccessLevel", null)
                        .WithMany()
                        .HasForeignKey("AccessLevelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BLAZAM.Database.Models.Permissions.PermissionMapping", null)
                        .WithMany()
                        .HasForeignKey("PermissionMapsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppUserChatRoom", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.Chat.ChatRoom", null)
                        .WithMany()
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BLAZAM.Database.Models.User.AppUser", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BLAZAM.Database.Models.ActiveDirectoryFieldObjectType", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.CustomActiveDirectoryField", null)
                        .WithMany("ObjectTypes")
                        .HasForeignKey("CustomActiveDirectoryFieldId");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.AutomationRuleExcludedGroupSid", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.Rules.GlobalAutomationRuleSettings", null)
                        .WithMany("ExcludedGroups")
                        .HasForeignKey("GlobalAutomationRuleSettingsId");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Chat.ChatMessage", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.Chat.ChatRoom", "ChatRoom")
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BLAZAM.Database.Models.User.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Chat.UnreadChatMessage", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.Chat.ChatMessage", "ChatMessage")
                        .WithMany("NotReadBy")
                        .HasForeignKey("ChatMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatMessage");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Notifications.NotificationSubscription", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.User.AppUser", "User")
                        .WithMany("NotificationSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Notifications.SubscriptionNotificationType", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.Notifications.NotificationSubscription", "NotificationSubscription")
                        .WithMany("NotificationTypes")
                        .HasForeignKey("NotificationSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationSubscription");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Notifications.SubscriptionWebHookType", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.Notifications.WebHookSubscription", "WebHookSubscription")
                        .WithMany("NotificationTypes")
                        .HasForeignKey("WebHookSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebHookSubscription");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Notifications.WebHookAttempt", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.Notifications.WebHookSubscription", "WebHookSubscription")
                        .WithMany("WebHookAttempts")
                        .HasForeignKey("WebHookSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebHookSubscription");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Permissions.ActionAccessMapping", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.Permissions.AccessLevel", null)
                        .WithMany("ActionMap")
                        .HasForeignKey("AccessLevelId");

                    b.HasOne("BLAZAM.Database.Models.Permissions.ObjectAction", "ObjectAction")
                        .WithMany()
                        .HasForeignKey("ObjectActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjectAction");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Permissions.FieldAccessMapping", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.CustomActiveDirectoryField", "CustomField")
                        .WithMany()
                        .HasForeignKey("CustomFieldId");

                    b.HasOne("BLAZAM.Database.Models.Permissions.FieldAccessLevel", "FieldAccessLevel")
                        .WithMany()
                        .HasForeignKey("FieldAccessLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BLAZAM.Database.Models.ActiveDirectoryField", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId");

                    b.Navigation("CustomField");

                    b.Navigation("Field");

                    b.Navigation("FieldAccessLevel");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Permissions.ObjectAccessMapping", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.Permissions.ObjectAccessLevel", "ObjectAccessLevel")
                        .WithMany("ObjectAccessMappings")
                        .HasForeignKey("ObjectAccessLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjectAccessLevel");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Rules.AutomationRuleAction", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.Rules.AutomationRule", null)
                        .WithMany("Actions")
                        .HasForeignKey("AutomationRuleId");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Rules.AutomationRuleActionFieldValue", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.Rules.AutomationRuleAction", "AutomationRuleAction")
                        .WithMany("FieldValues")
                        .HasForeignKey("AutomationRuleActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BLAZAM.Database.Models.CustomActiveDirectoryField", "CustomField")
                        .WithMany()
                        .HasForeignKey("CustomFieldId");

                    b.HasOne("BLAZAM.Database.Models.ActiveDirectoryField", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId");

                    b.Navigation("AutomationRuleAction");

                    b.Navigation("CustomField");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Rules.AutomationRuleAndFilter", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.CustomActiveDirectoryField", "CustomField")
                        .WithMany()
                        .HasForeignKey("CustomFieldId");

                    b.HasOne("BLAZAM.Database.Models.ActiveDirectoryField", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId");

                    b.HasOne("BLAZAM.Database.Models.Rules.AutomationRuleOrFilter", "OrFilter")
                        .WithMany("AndFilters")
                        .HasForeignKey("OrFilterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomField");

                    b.Navigation("Field");

                    b.Navigation("OrFilter");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Rules.AutomationRuleGroupSid", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.Rules.AutomationRuleAction", "AutomationRuleAction")
                        .WithMany("GroupSids")
                        .HasForeignKey("AutomationRuleActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutomationRuleAction");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Rules.AutomationRuleOrFilter", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.Rules.AutomationRule", "AutomationRule")
                        .WithMany("Filters")
                        .HasForeignKey("AutomationRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutomationRule");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Templates.DirectoryTemplate", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.Templates.DirectoryTemplate", "ParentTemplate")
                        .WithMany()
                        .HasForeignKey("ParentTemplateId");

                    b.Navigation("ParentTemplate");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Templates.DirectoryTemplateFieldValue", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.CustomActiveDirectoryField", "CustomField")
                        .WithMany()
                        .HasForeignKey("CustomFieldId");

                    b.HasOne("BLAZAM.Database.Models.Templates.DirectoryTemplate", null)
                        .WithMany("FieldValues")
                        .HasForeignKey("DirectoryTemplateId");

                    b.HasOne("BLAZAM.Database.Models.ActiveDirectoryField", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId");

                    b.Navigation("CustomField");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Templates.DirectoryTemplateGroup", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.Templates.DirectoryTemplate", null)
                        .WithMany("AssignedGroupSids")
                        .HasForeignKey("DirectoryTemplateId");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.User.ApiToken", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.User.AppUser", "User")
                        .WithMany("APITokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.User.NotificationMessage", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.User.AppUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.User.ReadNewsItem", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.User.AppUser", "User")
                        .WithMany("ReadNewsItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.User.UserDashboardWidget", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.User.AppUser", "User")
                        .WithMany("DashboardWidgets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.User.UserFavoriteEntry", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.User.AppUser", "User")
                        .WithMany("FavoriteEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.User.UserNotification", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.User.NotificationMessage", "Notification")
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BLAZAM.Database.Models.User.AppUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PermissionDelegatePermissionMapping", b =>
                {
                    b.HasOne("BLAZAM.Database.Models.Permissions.PermissionDelegate", null)
                        .WithMany()
                        .HasForeignKey("PermissionDelegatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BLAZAM.Database.Models.Permissions.PermissionMapping", null)
                        .WithMany()
                        .HasForeignKey("PermissionsMapsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Chat.ChatMessage", b =>
                {
                    b.Navigation("NotReadBy");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Chat.ChatRoom", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.CustomActiveDirectoryField", b =>
                {
                    b.Navigation("ObjectTypes");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Notifications.NotificationSubscription", b =>
                {
                    b.Navigation("NotificationTypes");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Notifications.WebHookSubscription", b =>
                {
                    b.Navigation("NotificationTypes");

                    b.Navigation("WebHookAttempts");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Permissions.AccessLevel", b =>
                {
                    b.Navigation("ActionMap");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Permissions.ObjectAccessLevel", b =>
                {
                    b.Navigation("ObjectAccessMappings");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Rules.AutomationRule", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Filters");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Rules.AutomationRuleAction", b =>
                {
                    b.Navigation("FieldValues");

                    b.Navigation("GroupSids");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Rules.AutomationRuleOrFilter", b =>
                {
                    b.Navigation("AndFilters");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Rules.GlobalAutomationRuleSettings", b =>
                {
                    b.Navigation("ExcludedGroups");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.Templates.DirectoryTemplate", b =>
                {
                    b.Navigation("AssignedGroupSids");

                    b.Navigation("FieldValues");
                });

            modelBuilder.Entity("BLAZAM.Database.Models.User.AppUser", b =>
                {
                    b.Navigation("APITokens");

                    b.Navigation("DashboardWidgets");

                    b.Navigation("FavoriteEntries");

                    b.Navigation("NotificationSubscriptions");

                    b.Navigation("Notifications");

                    b.Navigation("ReadNewsItems");
                });
#pragma warning restore 612, 618
        }
    }
}
