name: SonarQube
on:
  workflow_dispatch:
  push:
    branches:
      - v1-Dev
      - v1-Nightly
      - v1-Stable
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    permissions:
      contents: read
    runs-on: windows-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarQube Cloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarQube Cloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"Blazam-App_BLAZAM" /o:"blazam-app" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.scanner.scanAll=false /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" /d:sonar.coverage.exclusions="**/*.razor.cs,**/*.razor.g.cs,**/_Imports.razor.g.cs"
          dotnet build
          dotnet test .\BLAZAM.Tests\BLAZAM.Tests.csproj --no-build --collect:"XPlat Code Coverage" --results-directory ./TestResults/BLAZAM.Tests/ -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
          dotnet test .\BLAZAMCommon.Tests\BLAZAMCommon.Tests.csproj --no-build --collect:"XPlat Code Coverage" --results-directory ./TestResults/BLAZAMCommon.Tests/ -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
          dotnet test .\BLAZAMDatabase.Tests\BLAZAMDatabase.Tests.csproj --no-build --collect:"XPlat Code Coverage" --results-directory ./TestResults/BLAZAMDatabase.Tests/ -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"