name: Publish and Release

on:
  workflow_dispatch:
  push:
    branches:
      - Beta-Nightly
    

jobs:
  build:
    runs-on: windows-latest
   
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build application
        run: dotnet publish -c Release -o bin\Publish
      - name: Set assembly version as environment variable
        shell: pwsh
        id: get_version
        run: |
          $file = "bin\Publish\BLAZAM.dll";
          $versionInfo = (Get-Item $file).VersionInfo
          $fileVersion = $versionInfo.FileVersion
          $productVersion = $versionInfo.ProductVersion
          echo "##vso[task.setvariable variable=ASSEMBLY_VERSION]$fileVersion.$productVersion"
          echo "ASSEMBLY_VERSION=$fileVersion.$productVersion" >> $GITHUB_ENV
      - name: Show Version
        run: echo $ASSEMBLY_VERSION
      - name: Compress files
        run: Compress-Archive -Path bin\Publish\* -DestinationPath blazam-nightly.zip
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: $ASSEMBLY_VERSION
          body: Automated release created by GitHub Actions
          draft: true
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: blazam-nightly.zip
          asset_name: blazam-nightly.zip
          asset_content_type: application/zip
