name: Build v1 Dev

on:
  workflow_dispatch:
  push:
    branches:
      - v1-Dev
    

jobs:
  build:
    runs-on: windows-latest
   
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache Nuget Packages
        uses: actions/cache@v1
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Setup .NET Core SDK 8
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build application (Debug)
        run: dotnet build -c Debug
      - name: Setup Playwright
        shell: pwsh
        run: |
          PlaywrightTests/bin/Debug/net8.0/playwright.ps1 install; 
          
      - name: Test application
        run: dotnet test -c Release

      - name: Build application (Release)
        run: dotnet publish -c Release -o bin/publish BLAZAM/BLAZAM.csproj
      

      - name: Set assembly version as environment variable
        shell: pwsh
        id: get_version
        run: |
          $file = "bin/publish/BLAZAM.dll";
          $versionInfo = (Get-Item $file).VersionInfo
          $fileVersion = $versionInfo.FileVersion
          $productVersion = $versionInfo.ProductVersion
          echo "ASSEMBLY_VERSION=$fileVersion.$productVersion" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      - name: Show Version
        run: echo $env.ASSEMBLY_VERSION


      - name: Compress files
        run: Compress-Archive -Path bin/publish/* -DestinationPath blazam-dev-v${{ env.ASSEMBLY_VERSION }}.zip


      # For Linux
      #- name: "Compress files"
      #  uses: montudor/action-zip@v1
      #  with:
      #    args: zip -qq -r blazam-dev.zip bin/publish
      
      - name: Update dev release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: 'Dev1'
          name: 'Dev1'
          prerelease: true
          body: This release is highly unstable. Expect bugs and crashes on this branch. Developers Only!
          files: |
            ./blazam-dev-v${{ env.ASSEMBLY_VERSION }}.zip
