# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions


name: Build and deploy Windows Demo

on:
  push:
    branches:
      - v1-Nightly
  workflow_dispatch:

jobs:
  build:
    runs-on: Demo
    permissions: write-all

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 8
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x
      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Shutdown Demo Website
        shell: pwsh
        run: |
          New-Item -Path "C:\inetpub\demo.blazam.org" -Name "app_offline.htm" -ItemType "file" -Force
          Start-Sleep -Seconds 5

      - name: dotnet publish
        run: dotnet publish -c Release -o C:\inetpub\demo.blazam.org BLAZAM/BLAZAM.csproj

      - name: Restart Demo Website
        shell: pwsh
        run: |
          Remove-Item -Path "C:\inetpub\demo.blazam.org\app_offline.htm" -Force