# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions


name: Build and deploy ASP.Net Core app to Azure Web App - blazam

on:
  push:
    branches:
      - v1-Nightly
  workflow_dispatch:

jobs:
  build:
    runs-on: Demo
    permissions: write-all

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 8
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x
      - name: Build with dotnet
        run: dotnet build --configuration Release

     

      - name: Shutdown Demo Website
        shell: pwsh
        run: |
          New-Item -Path C:\inetpub\wwwroot -Name "app_offline.htm" -ItemType "file" -ErrorAction Continue

      - name: dotnet publish
        run: dotnet publish -c Release -o C:\inetpub\wwwroot BLAZAM/BLAZAM.csproj

      - name: Restart Demo Website
        shell: pwsh
        run: |
          Remove-Item -Path C:\inetpub\wwwroot\app_offline.htm

     

 