# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions


name: Deploy Linux Demo Website

on:
  push:
    branches:
      - v1-Dev-Beta
  workflow_dispatch:

jobs:
  build:
    runs-on: LinuxDemo
    permissions: write-all

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 8
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x
      - name: Build with dotnet
        run: dotnet build --configuration Release

     

      - name: Shutdown Demo Website
        shell: bash
        run: systemctl stop blazam.service

      - name: dotnet publish
        run: dotnet publish -c Release -o /opt/blazam BLAZAM/BLAZAM.csproj

      - name: Restart Demo Website
        shell: bash
        run: systemctl start blazam.service

     

 