name: Publish and Release Nightly

on:
  workflow_dispatch:
  push:
    branches:
      - Beta-Nightly
    

jobs:
  build:
    runs-on: windows-latest
   
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache Nuget Packages
        uses: actions/cache@v1
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build application
        run: dotnet publish -c Release -o bin\Publish
      - name: Set assembly version as environment variable
        shell: pwsh
        id: get_version
        run: |
          $file = "bin\Publish\BLAZAM.dll";
          $versionInfo = (Get-Item $file).VersionInfo
          $fileVersion = $versionInfo.FileVersion
          $productVersion = $versionInfo.ProductVersion
          echo "ASSEMBLY_VERSION=$fileVersion.$productVersion" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      - name: Show Version
        run: echo $env.ASSEMBLY_VERSION
      - name: Compress files
        run: Compress-Archive -Path bin\Publish\* -DestinationPath blazam-nightly-v${{ env.ASSEMBLY_VERSION }}.zip
     
      #- name: Create Release
      #  id: create_release
      #  uses: actions/create-release@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        
      #  with:
      #    tag_name: Nightly
      #    release_name: Nightly
      #    body: Automated release created by GitHub Actions
      #    draft: false
      #    prerelease: true
     

      #- name: Upload Release Asset
      #  id: upload-release-asset
      #  uses: actions/upload-release-asset@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      #  with:
      #    upload_url: ${{ steps.create_release.outputs.upload_url }}
      #    asset_path: blazam-nightly-v${{ env.ASSEMBLY_VERSION }}.zip
      #    asset_name: blazam-nightly-v${{ env.ASSEMBLY_VERSION }}.zip
      #    asset_content_type: application/zip



      - name: Get Release ID
        id: get_release_id
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          command: find
          args: |
            owner=Blazam-App
            repo=BLAZAM
            tag=Nightly

      - name: Replace Asset
        uses: actions/upload-artifact@v2
        with:
          name: Nightly.zip
          path:  blazam-nightly-v${{ env.ASSEMBLY_VERSION }}.zip

      - name: Delete Old Asset
        run: |
          curl \
            -X DELETE \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/Blazam-App/BLAZAM/releases/assets/Nightly.zip"

      - name: Upload New Asset
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: $(file -b --mime-type  blazam-nightly-v${{ env.ASSEMBLY_VERSION }}.zip)" \
            --data-binary "@ blazam-nightly-v${{ env.ASSEMBLY_VERSION }}.zip" \
            "https://uploads.github.com/repos/Blazam-App/BLAZAM/releases/RELEASE_ID/assets?name=Nightly.zip"
        env:
          RELEASE_ID: ${{ steps.get_release_id.outputs.id }}
