name: Publish and Release Nightly

on:
  workflow_dispatch:
  push:
    branches:
      - Beta-Nightly
    

jobs:
  build:
    runs-on: ubuntu-latest
   
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache Nuget Packages
        uses: actions/cache@v1
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build application
        run: dotnet publish -c Release -o bin/publish

      - name: "Compress files"
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r blazam-nightly.zip bin/publish

      - name: Update nightly release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.RELEASE_TOKEN }}
          file: blazam-nightly.zip
          asset_name: blazam-nightly.zip
          tag: Nightly
          overwrite: true
